[versions]
agp = "8.7.1"
docviewer = "3.0.3"
kotlin = "2.0.21"
appcompat = "1.7.0"

[libraries]
docviewer = { module = "com.github.Victor2018:DocViewer", version.ref = "docviewer" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

